# Generated by Django 5.1.2 on 2024-10-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='место, в котором выполняется привычка', max_length=200, verbose_name='место')),
                ('time', models.TimeField(help_text='время, когда выполняется привычка', verbose_name='время')),
                ('activity', models.CharField(help_text='действия, которое представляет собой привычка', max_length=500, verbose_name='действие')),
                ('is_pleasant_sign', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('regularity', models.CharField(default='ежедневная', max_length=200, verbose_name='периодичность')),
                ('award', models.CharField(blank=True, max_length=500, null=True, verbose_name='вознаграждение')),
                ('time_spent', models.DurationField(blank=True, help_text='потраченное время на выполнение привычки', null=True, verbose_name='потраченное время')),
                ('is_public', models.BooleanField(verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
