# Generated by Django 5.1.2 on 2024-10-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('pk',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
